ci

diff --git a/.github/workflows/pytest-coverage.yml b/.github/workflows/pytest-coverage.yml
--- a/.github/workflows/pytest-coverage.yml
+++ b/.github/workflows/pytest-coverage.yml
@@ -1,49 +1,47 @@
 ---
+- name: pytester-cov
+  uses: alexanderdamiani/pytester-cov@v1.2.1
+  on: [push, pull_request] # yamllint disable-line rule:truthy
+  jobs:
+    build:
+      runs-on: ubuntu-latest
+      env:
+        COVERAGE_SINGLE: 60
+        COVERAGE_TOTAL: 60
 
-name: pytester-cov
-uses: alexanderdamiani/pytester-cov@v1.2.1
-on: [push, pull_request]  # yamllint disable-line rule:truthy
-jobs:
-  build:
+      steps:
+        - name: setup
+          uses: actions/checkout@v2
+        - name: Set up Python 3.9
+          uses: actions/setup-python@v2
+          with:
+            python-version: 3.9
+        - name: Poetry Install
+          uses: knowsuchagency/poetry-install@v2
 
-    runs-on: ubuntu-latest
-    env:
-      COVERAGE_SINGLE: 60
-      COVERAGE_TOTAL: 60
+        - name: pytest
+          id: pytest
+          uses: alexanderdamiani/pytester-cov@v1.2.0
+          with:
+            pytest-root-dir: "."
+            cov-omit-list: "test/*, temp/main3.py, temp/main4.py"
+            cov-threshold-single: ${{ env.COVERAGE_SINGLE }}
+            cov-threshold-total: ${{ env.COVERAGE_TOTAL }}
 
-    steps:
-      - name: setup
-        uses: actions/checkout@v2
-      - name: Set up Python 3.9
-        uses: actions/setup-python@v2
-        with:
-          python-version: 3.9
-      - name: Poetry Install
-        uses: knowsuchagency/poetry-install@v2
+        - name: Coverage single fail - exit
+          if: ${{ steps.pytester-cov.outputs.cov-threshold-single-fail == 'true' }} # yamllint disable-line rule:line-length
+          # yamllint disable rule:line-length
+          run: |
+            echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-single-fail }}"
+            exit 1
 
-      - name: pytest
-        id: pytest
-        uses: alexanderdamiani/pytester-cov@v1.2.0
-        with:
-          pytest-root-dir: '.'
-          cov-omit-list: 'test/*, temp/main3.py, temp/main4.py'
-          cov-threshold-single: ${{ env.COVERAGE_SINGLE }}
-          cov-threshold-total: ${{ env.COVERAGE_TOTAL }}
-
-      - name: Coverage single fail - exit
-        if: ${{ steps.pytester-cov.outputs.cov-threshold-single-fail == 'true' }}  # yamllint disable-line rule:line-length
+        - name: Coverage total fail - exit
+          if: ${{ steps.pytester-cov.outputs.cov-threshold-total-fail == 'true' }}
+          run: |
+            echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-total-fail }}"
+            exit 1
         # yamllint disable rule:line-length
-        run: |
-          echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-single-fail }}"
-          exit 1
-
-      - name: Coverage total fail - exit
-        if: ${{ steps.pytester-cov.outputs.cov-threshold-total-fail == 'true' }}
-        run: |
-          echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-total-fail }}"
-          exit 1
-      # yamllint disable rule:line-length
-      - name: Commit pytest coverage table
-        uses: peter-evans/commit-comment@v1
-        with:
-          body: ${{ steps.pytester-cov.outputs.output-table }}
+        - name: Commit pytest coverage table
+          uses: peter-evans/commit-comment@v1
+          with:
+            body: ${{ steps.pytester-cov.outputs.output-table }}
